### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by rgreinho**
* Use /etc/profile.d/ for system wide installations

When setting up system wide environmental variables it is recommended to
place your configuration in a shell script within /etc/profile.d.

* Install git

As Git is a requirement to run this role we must ensure that it is present
on the system.

### CODE REVIEW

**Comment by sbani** [comment]
Hey @rgreinho,

first thanks for your suggestions.

Git is part of the [Ansible core](http://docs.ansible.com/ansible/git_module.html#this-is-a-core-module) and that is why you do not need to install it. 

3e540ca looks good, but I'm not that familiar with *nix. I have to check it tomorrow. 

I should add a test for `liquidprompt_enable_all_users = true`. Or you can do that if you want to. Would be nice!

**Comment by rgreinho** [comment]
I agree that the git module is part of ansible core, but if you look at the page you linked, in the ``Requirements`` section it says: ``git (the command line tool)``. So if you do not install the command line tool, the ansible module will fail.

Regarding 3e540ca, it works with Debian like and Red Hat like system. I have not tested with other ones.

Can you clarify what you mean by : "I should add a test for ``liquidprompt_enable_all_users = true``."?

**Comment by sbani** [comment]
I'm quite confused... I thought that git is always installed. But we can add it. Makes sense.

Look at [.travis.yml]https://github.com/sbani/ansible-role-liquidprompt/blob/master/.travis.yml). You see some tests here, but only for the case of `liquidprompt_enable_all_users = false`.

**Comment by rgreinho** [comment]
Ok, I added a test for ``liquidprompt_enable_all_users = true``.

**Comment by sbani** [comment]
Thx man.
Looks good. Would be nice if you add an empty line at the end of the file in future.

**Comment by rgreinho** [comment]
Thanks for merging. I added a line to almost all files cause it was not there before ;)

**Comment by sbani** [comment]
Ohhhhhhh. haha sorry.

**Pull request merged**
